export const images = {
  background: "./assets/background.png",
  foreground: "./assets/foreground.png",
  ground: "./assets/ground.png",
  highHill: "./assets/highHill.png",
  smallHill: "./assets/smallHill.png",
  parseGround: "./assets/parseGround.png",
  platform: "./assets/platform.png",
  reverseIdle: "./assets/reverseIdle.png",
  reverseJump: "./assets/reverseJump.png",
  reverseParachute: "./assets/reverseParachute.png",
  reverseWalk: "./assets/reverseWalk.png",
  spriteIdle: "./assets/spriteIdle.png",
  spriteJump: "./assets/spriteJump.png",
  spriteParachute: "./assets/spriteParachute.png",
  spriteWalk: "./assets/spriteWalk.png",
  ground_section01: "./assets/ground_section01.png",
  ground_section02: "./assets/ground_section02.png",
};
